var Screen0;
function Pantalla() {
    this.Inicio = function () {
        this.Navegador();
        this.NavegadorAnonimo();
        this.PreLogIn();
        this.PantallaInicio();
        this.PieDePagina();
    };
    this.Navegador = function () {
        var nav = document.getElementById('nav');
        var html = "";
        html += "<nav class='navbar navbar-expand-lg navbar-dark bg-gradient-custom'>";
        html += "  <img src='Imagenes/Logos/escudo.png' class='rounded-circle img-fluid mr-2 d-none d-md-inline' style='height: 4rem;'>";
        html += "  <button class='btn navbar-brand d-none d-md-inline' onclick='Screen0.PantallaInicio();'><h1>Saint Jean - Provincias</h1></button>";
        html += "  <button class='navbar-toggler' type='button' data-toggle='collapse' data-target='#navbarColor01' aria-controls='navbarColor01' aria-expanded='false' aria-label='Toggle navigation'>";
        html += "    <span class='navbar-toggler-icon'></span>";
        html += "  </button>";
        html += "  <div class='collapse navbar-collapse' id='navbarColor01'>";
        html += "    <ul id='menuBar' class='navbar-nav mr-auto'>";
        html += "    </ul>";
        html += "    <div id='logUser'>";
        html += "    </div>";
        html += "    <button type='button' class='btn btn-default btn-circle btn-lg' onclick='Screen0.PantallaContacto();' />";
        html += "       <img src='Imagenes/Iconos/support.png' class='img-fluid' style='height: 3rem;' title='Ayuda' />";
        html += "    </button>";
        html += "  </div>";
        html += "</nav>";
        nav.innerHTML = html;
    };
    this.NavegadorAnonimo = function () {
        var menu = document.getElementById('menuBar');
        var html = "";
        html += "      <li class='nav-item dropdown active'>";
        html += "	    <a class='nav-link dropdown-toggle' data-toggle='dropdown' href='#' role='button' aria-haspopup='true' aria-expanded='false'>Noroeste</a>";
        html += "	    <div class='dropdown-menu'>";
        html += "	      <button class='dropdown-item' onclick='Event0.ProvinciaAnonimo(12);'>La Rioja</button>";
        html += "	      <button class='dropdown-item' onclick='Event0.ProvinciaAnonimo(3);'>Catamarca</button>";
        html += "	      <button class='dropdown-item' onclick='Event0.ProvinciaAnonimo(22);'>Santiago del Estero</button>";
        html += "	      <button class='dropdown-item' onclick='Event0.ProvinciaAnonimo(24);'>Tucum&aacute;n</button>";
        html += "	      <button class='dropdown-item' onclick='Event0.ProvinciaAnonimo(17);'>Salta</button>";
        html += "	      <button class='dropdown-item' onclick='Event0.ProvinciaAnonimo(10);'>Jujuy</button>";
        html += "	    </div>";
        html += "	  </li>";
        html += "      <li class='nav-item dropdown'>";
        html += "	    <a class='nav-link dropdown-toggle' data-toggle='dropdown' href='#' role='button' aria-haspopup='true' aria-expanded='false'>Noreste</a>";
        html += "	    <div class='dropdown-menu'>";
        html += "	      <button class='dropdown-item' onclick='Event0.ProvinciaAnonimo(7);'>Corrientes</button>";
        html += "	      <button class='dropdown-item' onclick='Event0.ProvinciaAnonimo(8);'>Entre R&iacute;os</button>";
        html += "	      <button class='dropdown-item' onclick='Event0.ProvinciaAnonimo(14);'>Misiones</button>";
        html += "	      <button class='dropdown-item' onclick='Event0.ProvinciaAnonimo(4);'>Chaco</button>";
        html += "	      <button class='dropdown-item' onclick='Event0.ProvinciaAnonimo(9);'>Formosa</button>";
        html += "	    </div>";
        html += "	  </li>";
        html += "	  <li class='nav-item dropdown'>";
        html += "	    <a class='nav-link dropdown-toggle' data-toggle='dropdown' href='#' role='button' aria-haspopup='true' aria-expanded='false'>Cuyo</a>";
        html += "	    <div class='dropdown-menu'>";
        html += "	      <button class='dropdown-item' onclick='Event0.ProvinciaAnonimo(19);'>San Lu&iacute;s</button>";
        html += "	      <button class='dropdown-item' onclick='Event0.ProvinciaAnonimo(18);'>San Juan</button>";
        html += "	      <button class='dropdown-item' onclick='Event0.ProvinciaAnonimo(13);'>Mendoza</button>";
        html += "	    </div>";
        html += "	  </li>";
        html += "	  <li class='nav-item dropdown'>";
        html += "	    <a class='nav-link dropdown-toggle' data-toggle='dropdown' href='#' role='button' aria-haspopup='true' aria-expanded='false'>Pampeana</a>";
        html += "	    <div class='dropdown-menu'>";
        html += "	      <button class='dropdown-item' onclick='Event0.ProvinciaAnonimo(1);'>Buenos Aires</button>";
        html += "	      <button class='dropdown-item' onclick='Event0.ProvinciaAnonimo(2);'>Ciudad Aut&oacute;noma de Buenos Aires</button>";
        html += "	      <button class='dropdown-item' onclick='Event0.ProvinciaAnonimo(6);'>C&oacute;rdoba</button>";
        html += "	      <button class='dropdown-item' onclick='Event0.ProvinciaAnonimo(21);'>Santa Fe</button>";
        html += "	      <button class='dropdown-item' onclick='Event0.ProvinciaAnonimo(11);'>La Pampa</button>";
        html += "	    </div>";
        html += "	  </li>";
        html += "	  <li class='nav-item dropdown'>";
        html += "	    <a class='nav-link dropdown-toggle' data-toggle='dropdown' href='#' role='button' aria-haspopup='true' aria-expanded='false'>Patagonia</a>";
        html += "	    <div class='dropdown-menu'>";
        html += "	      <button class='dropdown-item' onclick='Event0.ProvinciaAnonimo(16);'>Rio Negro</button>";
        html += "	      <button class='dropdown-item' onclick='Event0.ProvinciaAnonimo(20);'>Santa Cruz</button>";
        html += "	      <button class='dropdown-item' onclick='Event0.ProvinciaAnonimo(5);'>Chubut</button>";
        html += "	      <button class='dropdown-item' onclick='Event0.ProvinciaAnonimo(15);'>Neuqu&eacute;n</button>";
        html += "	      <button class='dropdown-item' onclick='Event0.ProvinciaAnonimo(23);'>Tierra del Fuego</button>";
        html += "	    </div>";
        html += "	  </li>";
        menu.innerHTML = html;
    };
    this.NavegadorGrupo = function () {
        var menu = document.getElementById('menuBar');
        var html = "";
        html += "	  <li class='nav-item dropdown active'>";
        switch (Usuario.Nombre) {
            case "La Rioja":
                html += "	    <a class='nav-link dropdown-toggle' data-toggle='dropdown' href='#' role='button' aria-haspopup='true' aria-expanded='false'>Noroeste</a>";
                html += "	    <div class='dropdown-menu'>";
                html += "	      <button class='dropdown-item' type='button' onclick='Event0.ProvinciaGrupo(12);'>La Rioja</button>";
                html += "	    </div>";
                break;
            case "Catamarca":
                html += "	    <a class='nav-link dropdown-toggle' data-toggle='dropdown' href='#' role='button' aria-haspopup='true' aria-expanded='false'>Noroeste</a>";
                html += "	    <div class='dropdown-menu'>";
                html += "	      <button class='dropdown-item' type='button' onclick='Event0.ProvinciaGrupo(3);'>Catamarca</button>";
                html += "	    </div>";
                break;
            case "Santiago del Estero":
                html += "	    <a class='nav-link dropdown-toggle' data-toggle='dropdown' href='#' role='button' aria-haspopup='true' aria-expanded='false'>Noroeste</a>";
                html += "	    <div class='dropdown-menu'>";
                html += "	      <button class='dropdown-item' type='button' onclick='Event0.ProvinciaGrupo(22);'>Santiago del Estero</button>";
                html += "	    </div>";
                break;
            case "Tucuman":
                html += "	    <a class='nav-link dropdown-toggle' data-toggle='dropdown' href='#' role='button' aria-haspopup='true' aria-expanded='false'>Noroeste</a>";
                html += "	    <div class='dropdown-menu'>";
                html += "	      <button class='dropdown-item' type='button' onclick='Event0.ProvinciaGrupo(24);'>Tucum&aacute;n</button>";
                html += "	    </div>";
                break;
            case "Salta":
                html += "	    <a class='nav-link dropdown-toggle' data-toggle='dropdown' href='#' role='button' aria-haspopup='true' aria-expanded='false'>Noroeste</a>";
                html += "	    <div class='dropdown-menu'>";
                html += "	      <button class='dropdown-item' type='button' onclick='Event0.ProvinciaGrupo(17);'>Salta</button>";
                html += "	    </div>";
                break;
            case "Jujuy":
                html += "	    <a class='nav-link dropdown-toggle' data-toggle='dropdown' href='#' role='button' aria-haspopup='true' aria-expanded='false'>Noroeste</a>";
                html += "	    <div class='dropdown-menu'>";
                html += "	      <button class='dropdown-item' type='button' onclick='Event0.ProvinciaGrupo(10);'>Jujuy</button>";
                html += "	    </div>";
                break;
            case "Entre Rios":
                html += "	    <a class='nav-link dropdown-toggle' data-toggle='dropdown' href='#' role='button' aria-haspopup='true' aria-expanded='false'>Noreste</a>";
                html += "	    <div class='dropdown-menu'>";
                html += "	      <button class='dropdown-item' type='button' onclick='Event0.ProvinciaGrupo(8);'>Entre R&iacute;os</button>";
                html += "	    </div>";
                break;
            case "Corrientes":
                html += "	    <a class='nav-link dropdown-toggle' data-toggle='dropdown' href='#' role='button' aria-haspopup='true' aria-expanded='false'>Noreste</a>";
                html += "	    <div class='dropdown-menu'>";
                html += "	      <button class='dropdown-item' type='button' onclick='Event0.ProvinciaGrupo(7);'>Corrientes</button>";
                html += "	    </div>";
                break;
            case "Misiones":
                html += "	    <a class='nav-link dropdown-toggle' data-toggle='dropdown' href='#' role='button' aria-haspopup='true' aria-expanded='false'>Noreste</a>";
                html += "	    <div class='dropdown-menu'>";
                html += "	      <button class='dropdown-item' type='button' onclick='Event0.ProvinciaGrupo(14);'>Misiones</button>";
                html += "	    </div>";
                break;
            case "Chaco":
                html += "	    <a class='nav-link dropdown-toggle' data-toggle='dropdown' href='#' role='button' aria-haspopup='true' aria-expanded='false'>Noreste</a>";
                html += "	    <div class='dropdown-menu'>";
                html += "	      <button class='dropdown-item' type='button' onclick='Event0.ProvinciaGrupo(4);'>Chaco</button>";
                html += "	    </div>";
                break;
            case "Formosa":
                html += "	    <a class='nav-link dropdown-toggle' data-toggle='dropdown' href='#' role='button' aria-haspopup='true' aria-expanded='false'>Noreste</a>";
                html += "	    <div class='dropdown-menu'>";
                html += "	      <button class='dropdown-item' type='button' onclick='Event0.ProvinciaGrupo(9);'>Formosa</button>";
                html += "	    </div>";
                break;
            case "San Luis":
                html += "	    <a class='nav-link dropdown-toggle' data-toggle='dropdown' href='#' role='button' aria-haspopup='true' aria-expanded='false'>Cuyo</a>";
                html += "	    <div class='dropdown-menu'>";
                html += "	      <button class='dropdown-item' type='button' onclick='Event0.ProvinciaGrupo(19);'>San Lu&iacute;s</button>";
                html += "	    </div>";
                break;
            case "San Juan":
                html += "	    <a class='nav-link dropdown-toggle' data-toggle='dropdown' href='#' role='button' aria-haspopup='true' aria-expanded='false'>Cuyo</a>";
                html += "	    <div class='dropdown-menu'>";
                html += "	      <button class='dropdown-item' type='button' onclick='Event0.ProvinciaGrupo(18);'>San Juan</button>";
                html += "	    </div>";
                break;
            case "Mendoza":
                html += "	    <a class='nav-link dropdown-toggle' data-toggle='dropdown' href='#' role='button' aria-haspopup='true' aria-expanded='false'>Cuyo</a>";
                html += "	    <div class='dropdown-menu'>";
                html += "	      <button class='dropdown-item' type='button' onclick='Event0.ProvinciaGrupo(13);'>Mendoza</button>";
                html += "	    </div>";
                break;
            case "Buenos Aires":
                html += "	    <a class='nav-link dropdown-toggle' data-toggle='dropdown' href='#' role='button' aria-haspopup='true' aria-expanded='false'>Pampeana</a>";
                html += "	    <div class='dropdown-menu'>";
                html += "	      <button class='dropdown-item' type='button' onclick='Event0.ProvinciaGrupo(1);'>Buenos Aires</button>";
                html += "	    </div>";
                break;
            case "Ciudad Autonoma de Buenos Aires":
                html += "	    <a class='nav-link dropdown-toggle' data-toggle='dropdown' href='#' role='button' aria-haspopup='true' aria-expanded='false'>Pampeana</a>";
                html += "	    <div class='dropdown-menu'>";
                html += "	      <button class='dropdown-item' type='button' onclick='Event0.ProvinciaGrupo(2);'>Ciudad Aut&oacute;noma de Buenos Aires</button>";
                html += "	    </div>";
                break;
            case "Cordoba":
                html += "	    <a class='nav-link dropdown-toggle' data-toggle='dropdown' href='#' role='button' aria-haspopup='true' aria-expanded='false'>Pampeana</a>";
                html += "	    <div class='dropdown-menu'>";
                html += "	      <button class='dropdown-item' type='button' onclick='Event0.ProvinciaGrupo(6);'>C&oacute;rdoba</button>";
                html += "	    </div>";
                break;
            case "Santa Fe":
                html += "	    <a class='nav-link dropdown-toggle' data-toggle='dropdown' href='#' role='button' aria-haspopup='true' aria-expanded='false'>Pampeana</a>";
                html += "	    <div class='dropdown-menu'>";
                html += "	      <button class='dropdown-item' type='button' onclick='Event0.ProvinciaGrupo(21);'>Santa Fe</button>";
                html += "	    </div>";
                break;
            case "La Pampa":
                html += "	    <a class='nav-link dropdown-toggle' data-toggle='dropdown' href='#' role='button' aria-haspopup='true' aria-expanded='false'>Pampeana</a>";
                html += "	    <div class='dropdown-menu'>";
                html += "	      <button class='dropdown-item' type='button' onclick='Event0.ProvinciaGrupo(11);'>La Pampa</button>";
                html += "	    </div>";
                break;
            case "Rio Negro":
                html += "	    <a class='nav-link dropdown-toggle' data-toggle='dropdown' href='#' role='button' aria-haspopup='true' aria-expanded='false'>Patagonia</a>";
                html += "	    <div class='dropdown-menu'>";
                html += "	      <button class='dropdown-item' type='button' onclick='Event0.ProvinciaGrupo(16);'>Rio Negro</button>";
                html += "	    </div>";
                break;
            case "Santa Cruz":
                html += "	    <a class='nav-link dropdown-toggle' data-toggle='dropdown' href='#' role='button' aria-haspopup='true' aria-expanded='false'>Patagonia</a>";
                html += "	    <div class='dropdown-menu'>";
                html += "	      <button class='dropdown-item' type='button' onclick='Event0.ProvinciaGrupo(20);'>Santa Cruz</button>";
                html += "	    </div>";
                break;
            case "Chubut":
                html += "	    <a class='nav-link dropdown-toggle' data-toggle='dropdown' href='#' role='button' aria-haspopup='true' aria-expanded='false'>Patagonia</a>";
                html += "	    <div class='dropdown-menu'>";
                html += "	      <button class='dropdown-item' type='button' onclick='Event0.ProvinciaGrupo(5);'>Chubut</button>";
                html += "	    </div>";
                break;
            case "Neuquen":
                html += "	    <a class='nav-link dropdown-toggle' data-toggle='dropdown' href='#' role='button' aria-haspopup='true' aria-expanded='false'>Patagonia</a>";
                html += "	    <div class='dropdown-menu'>";
                html += "	      <button class='dropdown-item' type='button' onclick='Event0.ProvinciaGrupo(15);'>Neuqu&eacute;n</button>";
                html += "	    </div>";
                break;
            case "Tierra del Fuego":
                html += "	    <a class='nav-link dropdown-toggle' data-toggle='dropdown' href='#' role='button' aria-haspopup='true' aria-expanded='false'>Patagonia</a>";
                html += "	    <div class='dropdown-menu'>";
                html += "	      <button class='dropdown-item' type='button' onclick='Event0.ProvinciaGrupo(23);'>Tierra del Fuego</button>";
                html += "	    </div>";
                break;
        }
        html += "	  </li>";
        html += "     <li class='nav-item'>";
        html += "	    <button class='btn nav-link' type='button' onclick='Screen0.EditarPerfil();'>Editar Perfil</button>";
        html += "     </li>";
        menu.innerHTML = html;
    };
    this.NavegadorMaestro = function () {
        var menu = document.getElementById('menuBar');
        var html = "";
        html += "      <li class='nav-item dropdown active'>";
        html += "	    <a class='nav-link dropdown-toggle' data-toggle='dropdown' href='#' role='button' aria-haspopup='true' aria-expanded='false'>Noroeste</a>";
        html += "	    <div class='dropdown-menu'>";
        html += "	      <button class='dropdown-item' type='button' onclick='Event0.ProvinciaMaestro(12)'>La Rioja</button>";
        html += "	      <button class='dropdown-item' type='button' onclick='Event0.ProvinciaMaestro(3)'>Catamarca</button>";
        html += "	      <button class='dropdown-item' type='button' onclick='Event0.ProvinciaMaestro(22)'>Santiago del Estero</button>";
        html += "	      <button class='dropdown-item' type='button' onclick='Event0.ProvinciaMaestro(24)'>Tucum&aacute;n</button>";
        html += "	      <button class='dropdown-item' type='button' onclick='Event0.ProvinciaMaestro(17)'>Salta</button>";
        html += "	      <button class='dropdown-item' type='button' onclick='Event0.ProvinciaMaestro(10)'>Jujuy</button>";
        html += "	    </div>";
        html += "	  </li>";
        html += "      <li class='nav-item dropdown'>";
        html += "	    <a class='nav-link dropdown-toggle' data-toggle='dropdown' href='#' role='button' aria-haspopup='true' aria-expanded='false'>Noreste</a>";
        html += "	    <div class='dropdown-menu'>";
        html += "	      <button class='dropdown-item' type='button' onclick='Event0.ProvinciaMaestro(7)'>Corrientes</button>";
        html += "	      <button class='dropdown-item' type='button' onclick='Event0.ProvinciaMaestro(8)'>Entre R&iacute;os</button>";
        html += "	      <button class='dropdown-item' type='button' onclick='Event0.ProvinciaMaestro(14)'>Misiones</button>";
        html += "	      <button class='dropdown-item' type='button' onclick='Event0.ProvinciaMaestro(4)'>Chaco</button>";
        html += "	      <button class='dropdown-item' type='button' onclick='Event0.ProvinciaMaestro(9)'>Formosa</button>";
        html += "	    </div>";
        html += "	  </li>";
        html += "	  <li class='nav-item dropdown'>";
        html += "	    <a class='nav-link dropdown-toggle' data-toggle='dropdown' href='#' role='button' aria-haspopup='true' aria-expanded='false'>Cuyo</a>";
        html += "	    <div class='dropdown-menu'>";
        html += "	      <button class='dropdown-item' type='button' onclick='Event0.ProvinciaMaestro(19)'>San Lu&iacute;s</button>";
        html += "	      <button class='dropdown-item' type='button' onclick='Event0.ProvinciaMaestro(18)'>San Juan</button>";
        html += "	      <button class='dropdown-item' type='button' onclick='Event0.ProvinciaMaestro(13)'>Mendoza</button>";
        html += "	    </div>";
        html += "	  </li>";
        html += "	  <li class='nav-item dropdown'>";
        html += "	    <a class='nav-link dropdown-toggle' data-toggle='dropdown' href='#' role='button' aria-haspopup='true' aria-expanded='false'>Pampeana</a>";
        html += "	    <div class='dropdown-menu'>";
        html += "	      <button class='dropdown-item' type='button' onclick='Event0.ProvinciaMaestro(1)'>Buenos Aires</button>";
        html += "	      <button class='dropdown-item' type='button' onclick='Event0.ProvinciaMaestro(2)'>Ciudad Aut&oacute;noma de Buenos Aires</button>";
        html += "	      <button class='dropdown-item' type='button' onclick='Event0.ProvinciaMaestro(6)'>C&oacute;rdoba</button>";
        html += "	      <button class='dropdown-item' type='button' onclick='Event0.ProvinciaMaestro(21)'>Santa Fe</button>";
        html += "	      <button class='dropdown-item' type='button' onclick='Event0.ProvinciaMaestro(11)'>La Pampa</button>";
        html += "	    </div>";
        html += "	  </li>";
        html += "	  <li class='nav-item dropdown'>";
        html += "	    <a class='nav-link dropdown-toggle' data-toggle='dropdown' href='#' role='button' aria-haspopup='true' aria-expanded='false'>Patagonia</a>";
        html += "	    <div class='dropdown-menu'>";
        html += "	      <button class='dropdown-item' type='button' onclick='Event0.ProvinciaMaestro(16)'>Rio Negro</button>";
        html += "	      <button class='dropdown-item' type='button' onclick='Event0.ProvinciaMaestro(20)'>Santa Cruz</button>";
        html += "	      <button class='dropdown-item' type='button' onclick='Event0.ProvinciaMaestro(5)'>Chubut</button>";
        html += "	      <button class='dropdown-item' type='button' onclick='Event0.ProvinciaMaestro(15)'>Neuqu&eacute;n</button>";
        html += "	      <button class='dropdown-item' type='button' onclick='Event0.ProvinciaMaestro(23)'>Tierra del Fuego</button>";
        html += "	    </div>";
        html += "	  </li>";
        html += "     <li class='nav-item'>";
        html += "	    <button class='btn nav-link' type='button' onclick='Event0.PantallaAlumnos();'>Alumnos</button>";
        html += "     </li>";
        html += "     <li class='nav-item'>";
        html += "	    <button class='btn nav-link' type='button' onclick='Screen0.EditarPerfil();'>Editar Perfil</button>";
        html += "     </li>";
        menu.innerHTML = html;
    };
    this.PreLogIn = function () {
        var logUser = document.getElementById('logUser');
        var html = "";
        html += "    <div class='form-inline justify-content-center my-1 my-lg-0'>";
        html += "      <input id='TBNombre' class='form-control my-1 mr-sm-1' type='text' placeholder='Usuario' name='TBNombre'>";
        html += "      <input id='TBClave' class='form-control my-1 mr-sm-1' type='password' placeholder='Contraseña' name='TBClave'>";
        html += "      <button class='btn btn-info shadow-sm my-1' onclick='Event0.IniciarSesion();'>Iniciar Sesi&oacute;n</button>";
        html += "      <button class='btn btn-info shadow-sm my-1 mx-1' onclick='Event0.Cancelar();'>Cancelar</button>";
        html += "    </div>";
        logUser.innerHTML = html;
    };
    this.PostLogIn = function () {
        var logUser = document.getElementById('logUser');
        var html = "";
        html += "   <div class='form-inline justify-content-center my-2 my-lg-0'>";
        html += "     <img id='IMGIconoPerfil' src='" + Usuario.Foto + "' class='rounded-circle img-fluid mr-2 d-none d-md-inline' style='height: 4rem; width: 4rem;'/>";
        html += "     <span class='d-none d-md-inline mr-2 h3 text-white'>" + Usuario.Nombre + " (" + Usuario.Rol.Nombre + ")" + "</span>";
        html += "     <button class='btn btn-info shadow-sm my-2 my-sm-0 mr-sm-2' onclick='Event0.CerrarSesion();'>Cerrar Sesi&oacute;n</button>";
        html += "   </div>";
        logUser.innerHTML = html;
    };
    this.PieDePagina = function () {
        var bot = document.getElementById('bot');
        var html = "";
        var d = new Date();
        html += "<hr/>";
        html += "<div class='container-fluid text-white text-center'>";
        html += "	<div class='row'>";
        html += "		<div class='col-12 mt-5'>";
        html += "			<p class='lead'>";
        html += "				Proyecto Saint Jean Provincias - " + d.getFullYear() + " &copy; Derechos Reservados<br/>";
        html += "				Instituto Superior de Formaci&oacute;n Docente y T&eacute;cnica Nº 114<br/>";
        html += "				'Jos&eacute; Gabriel Tupac Amaru II'";
        html += "			</p>";
        html += "		</div>";
        html += "	</div>";
        html += "	<div class='row'>";
        html += "		<div class='col-3'>";
        html += "			<p class='lead'>";
        html += "				Alumnos";
        html += "			</p>";
        html += "		</div>";
        html += "		<div class='col-3'>";
        html += "			<p class='lead'>";
        html += "				Profesores";
        html += "			</p>";
        html += "		</div>";
        html += "		<div class='col-6'>";
        html += "			<p class='lead'>";
        html += "				Acerca del proyecto";
        html += "			</p>";
        html += "		</div>";
        html += "	</div>";
        html += "	<div class='row'>";
        html += "		<div class='col-3'>";
        html += "			<p class='lead'>";
        html += "				Jonathan Martinez";
        html += "			</p>";
        html += "		</div>";
        html += "		<div class='col-3'>";
        html += "			<p class='lead'>";
        html += "				Jorge Docampo<br/>";
        html += "				Beatriz Gonzalez";
        html += "			</p>";
        html += "		</div>";
        html += "		<div class='col-6'>";
        html += "			<p class='lead'>";
        html += "				El presente proyecto consiste en la elaboraci&oacute;n de un software educativo desarrollado en un entorno web, ";
        html += "para una instituci&oacute;n de nivel secundario, que vincula distintos espacios curriculares del primer a&ntilde;o (Ciudadan&iacute;a, Ciencias ";
        html += "Sociales, Inform&aacute;tica, Lengua), introduciendo a docentes y alumnos en el manejo de TICs y la investigaci&oacute;n orientada, a trav&eacute;s de un trabajo colaborativo.";
        html += "			</p>";
        html += "		</div>";
        html += "	</div>";
        html += "</div>";
        bot.innerHTML = html;
    };
    this.PantallaInicio = function () {
        var mid = document.getElementById('mid');
        var html = "";
        html += "<div class='container mt-5'>";
        html += "   <div id='carouselProvinces' class='content-fluid carousel slide' data-ride='carousel'>";
        html += "     <ol class='carousel-indicators'>";
        html += "       <li data-target='#carouselProvinces' data-slide-to='0' class='active'></li>";
        html += "       <li data-target='#carouselProvinces' data-slide-to='1'></li>";
        html += "       <li data-target='#carouselProvinces' data-slide-to='2'></li>";
        html += "       <li data-target='#carouselProvinces' data-slide-to='3'></li>";
        html += "       <li data-target='#carouselProvinces' data-slide-to='4'></li>";
        html += "       <li data-target='#carouselProvinces' data-slide-to='5'></li>";
        html += "       <li data-target='#carouselProvinces' data-slide-to='6'></li>";
        html += "       <li data-target='#carouselProvinces' data-slide-to='7'></li>";
        html += "       <li data-target='#carouselProvinces' data-slide-to='8'></li>";
        html += "     </ol>";
        html += "     <div class='carousel-inner'>";
        html += "       <div class='carousel-item active'>";
        html += "   	  <img class='d-block w-100 img-fluid' src='Imagenes/Inicio/BuenosAiresObelisco.jpg'>";
        html += "   	  <div class='carousel-caption d-none d-md-block shadow-text'>";
        html += "   	    <h2>Buenos Aires - Obelisco</h2>";
        html += "   	    <h5>Caminando por las calles de la Ciudad de Buenos Aires, podr&aacute;s apreciar el obelisco en todo su esplendor</h5>";
        html += "   	  </div>";
        html += "   	</div>";
        html += "   	<div class='carousel-item'>";
        html += "   	  <img class='d-block w-100 img-fluid' src='Imagenes/Inicio/SantaCruzPeritoMoreno.jpg'>";
        html += "   	  <div class='carousel-caption d-none d-md-block shadow-text'>";
        html += "   	    <h2>Santa Cruz - Glaciar Perito Moreno</h2>";
        html += "   	    <h5>Un glaciar &uacute;nico en el mundo, el cual se encuentra en equilibrio natural</h5>";
        html += "   	  </div>";
        html += "   	</div>";
        html += "   	<div class='carousel-item'>";
        html += "   	  <img class='d-block w-100 img-fluid' src='Imagenes/Inicio/TucumanTafiDelValle.jpg'>";
        html += "   	  <div class='carousel-caption d-none d-md-block shadow-text'>";
        html += "   	    <h2>Tucum&aacute;n - Taf&iacute; del Valle</h2>";
        html += "   	    <h5>El jard&iacute;n de Argentina, catalogado de esta manera por todos sus habitantes</h5>";
        html += "   	  </div>";
        html += "   	</div>";
        html += "   	<div class='carousel-item'>";
        html += "   	  <img class='d-block w-100 img-fluid' src='Imagenes/Inicio/MisionesCataratasDelIguazu.jpg'>";
        html += "   	  <div class='carousel-caption d-none d-md-block shadow-text'>";
        html += "   	    <h2>Misiones - Cataratas del Iguaz&uacute;</h2>";
        html += "   	    <h5>Magestuosas e impactantes, las cataratas te dejar&aacute;n con la boca abierta al verlas a tan solo unos metros</h5>";
        html += "   	  </div>";
        html += "   	</div>";
        html += "   	<div class='carousel-item'>";
        html += "   	  <img class='d-block w-100 img-fluid' src='Imagenes/Inicio/ChubutLagoPuelo.jpg'>";
        html += "   	  <div class='carousel-caption d-none d-md-block shadow-text'>";
        html += "   	    <h2>Chubut - Lago Puelo</h2>";
        html += "   	    <h5>Un lugar donde encontrar&aacute;s la paz interior con solo una fotograf&iacute;a panor&aacute;mica visual</h5>";
        html += "   	  </div>";
        html += "   	</div>";
        html += "   	<div class='carousel-item'>";
        html += "   	  <img class='d-block w-100 img-fluid' src='Imagenes/Inicio/CordobaElDurazno.jpeg'>";
        html += "   	  <div class='carousel-caption d-none d-md-block shadow-text'>";
        html += "   	    <h2>C&oacute;rdoba - El Durazno</h2>";
        html += "   	    <h5>Un valle como ninguno, lleno de verde primavera y r&iacute;os que seducen</h5>";
        html += "   	  </div>";
        html += "   	</div>";
        html += "   	<div class='carousel-item'>";
        html += "   	  <img class='d-block w-100 img-fluid' src='Imagenes/Inicio/TierraDelFuegoFinDelMundo.jpg'>";
        html += "   	  <div class='carousel-caption d-none d-md-block shadow-text'>";
        html += "   	    <h2>Tierra del Fuego - Fin del Mundo</h2>";
        html += "   	    <h5>Un viaje de pel&iacute;cula, con vistas impresionantes de camino... al fin del mundo? Querr&aacute;s descubrirlo por tu cuenta</h5>";
        html += "   	  </div>";
        html += "   	</div>";
        html += "   	<div class='carousel-item'>";
        html += "   	  <img class='d-block w-100 img-fluid' src='Imagenes/Inicio/MendozaSanRafael.jpg'>";
        html += "   	  <div class='carousel-caption d-none d-md-block shadow-text'>";
        html += "   	    <h2>Mendoza - San Rafael</h2>";
        html += "   	    <h5>Caminando por las tierras del vino podr&aacute;s toparte con esta belleza que nos brinda la naturaleza</h5>";
        html += "   	  </div>";
        html += "   	</div>";
        html += "   	<div class='carousel-item'>";
        html += "   	  <img class='d-block w-100 img-fluid' src='Imagenes/Inicio/JujuyCerroDeLos7Colores.jpg'>";
        html += "   	  <div class='carousel-caption d-none d-md-block shadow-text'>";
        html += "   	    <h2>Jujuy - Cerro de los 7 Colores</h2>";
        html += "   	    <h5>Si cre&iacute;as que lo hab&iacute;as visto todo, no podr&aacute;s esperar a hacer trekking apreciando el paisaje</h5>";
        html += "   	  </div>";
        html += "   	</div>";
        html += "     </div>";
        html += "     <a class='carousel-control-prev' href='#carouselProvinces' role='button' data-slide='prev'>";
        html += "       <span class='carousel-control-prev-icon' aria-hidden='true'></span>";
        html += "       <span class='sr-only'>Previous</span>";
        html += "     </a>";
        html += "     <a class='carousel-control-next' href='#carouselProvinces' role='button' data-slide='next'>";
        html += "       <span class='carousel-control-next-icon' aria-hidden='true'></span>";
        html += "       <span class='sr-only'>Next</span>";
        html += "     </a>";
        html += "   </div>";
        html += "</div>";
        mid.innerHTML = html;
    };
    this.PantallaContacto = function () {
        var mid = document.getElementById('mid');
        var html = "";
        html += "<div class='container text-white mt-5' style='height: 60vh;'>";
        html += "   <div class='row align-items-center'>";
        html += "       <div class='col-12 d-block'>";
        html += "           <h1 style='font-style: italic;'>Contacto</h1>";
        html += "           <p class='lead'>En caso de surgir alg&uacute;n inconveniente, por favor envíenos un correo electrónico a nuestros e-mails personales.</p>";
        html += "           <p class='lead'>- jonathan25092509@gmail.com</p>";
        html += "           <h1 style='font-style: italic;'>Manual de Uso</h1>";
        html += "           <p class='lead'>Quiz&aacute;s leyendo el manual de uso pod&eacute;s encontrar alguna respuesta a tus dudas o problemas. El mismo pod&eacute;s descargarlo haciendo clic en el siguiente enlace: <a href='../Documentos/ManualDeUsuario.pdf' target='_blank' download='Manual_Saint_Jean_Provincias' class='text-dark' style='font-weight: bold;'>Descargar</a></p>";
        html += "       </div>";
        html += "   </div>";
        html += "</div>";
        mid.innerHTML = html;
    };
    this.ProvinciaAnonimo = function (Provincia) {
        var mid = document.getElementById('mid');
        var html = "";
        html += "<div class='container-fluid text-left text-white'>";
        html += "	<div class='row mt-5'>";
        html += "	  	<div class='col'>";
        html += "		  	<h2>" + Provincia.Nombre + "</h2>";
        html += "			<hr/>";
        html += "	  	</div>";
        html += "	</div>";
        html += "	<div class='row'>";
        html += "		<div class='col-xs-12 col-md-2 text-center'>";
        html += "			<img src='" + Provincia.Foto + "' alt='" + Provincia.Nombre + "' class='img-thumbnail img-fluid' style='height: 25rem;'>";
        html += "		</div>";
        html += "		<div class='col-xs-12 col-md-10 mt-2 align-self-center text-light'>";
        html += "		    <h3 >Capital: " + Provincia.Capital + "</h3>";
        html += "		    <h3 >Poblaci&oacute;n: " + Provincia.Poblacion + "</h3>";
        html += "		    <h3 >Cantidad de Senadores: " + Provincia.CantSenadores + "</h3>";
        html += "		    <h3 >Cantidad de Diputados: " + Provincia.CantDiputados + "</h3>";
        html += "		    <h3 >Superficie (Km2): " + Provincia.Superficie + "</h3>";
        html += "		</div>";
        html += "	</div>";
        html += "	<div class='row mt-5 mb-5'>";
        html += "		<div class='col-xs-12 col-md-9'>";
        html += "			<blockquote class='blockquote d-inline'>";
        html += "			  <h2 class='mb-0'>" + Provincia.Gobernador.Nombre + " " + Provincia.Gobernador.Apellido + " - Gobernador/a</h2>";
        html += "			</blockquote>";
        html += "			<hr/>";
        html += "			<h4>Per&iacute;odo de Gobierno: " + Provincia.Gobernador.PeriodoGobierno + "</h4>";
        html += "			<p class='lead'>" + Provincia.Gobernador.Historial + "</p>";
        html += "		</div>";
        html += "		<div class='col-xs-12 col-md-3 text-center align-self-center'>";
        html += "			<img src='" + Provincia.Gobernador.Foto + "' alt='" + Provincia.Gobernador.Nombre + " " + Provincia.Gobernador.Apellido + "' class='img-thumbnail img-fluid' style='height: 15rem;'>";
        html += "		</div>";
        html += "	</div>";
        html += "	<div class='row text-center mb-5 justify-content-center'>";
        if (Provincia.PuntosDeInteres.length > 0) {
            html += "		<div class='wrapper col-xs-12 col-lg-6'>";
            html += "			<h3>Puntos de Interes</h3>";
            html += "			<hr/>";
            html += "			<div id='carouselPuntosInteres' class='carousel slide' data-ride='carousel'>";
            html += "			  <ol class='carousel-indicators'>";
            for (var i = 0; i < Provincia.PuntosDeInteres.length; i++) {
                if (i === 0) {
                    html += "			    <li data-target='#carouselPuntosInteres' data-slide-to='" + i + "' class='active'></li>";
                    continue;
                }
                html += "			    <li data-target='#carouselPuntosInteres' data-slide-to='" + i + "'></li>";
            }
            html += "			  </ol>";
            html += "			  <div class='carousel-inner'>";
            for (var j = 0; j < Provincia.PuntosDeInteres.length; j++) {
                if (j === 0) {
                    html += "			    <div class='carousel-item active'>";
                }
                else {
                    html += "			    <div class='carousel-item'>";
                }
                html += "				  <img class='d-block w-100 img-fluid' src='" + Provincia.PuntosDeInteres[j].Foto + "' alt='Buenos Aires'>";
                html += "				  <div class='carousel-caption d-none d-md-block shadow-text'>";
                html += "				    <h2>" + Provincia.PuntosDeInteres[j].Nombre + "</h2>";
                html += "				    <h5>" + Provincia.PuntosDeInteres[j].Descripcion + "</h5>";
                html += "				  </div>";
                html += "				</div>";
            }
            html += "			  </div>";
            html += "			  <a class='carousel-control-prev' href='#carouselPuntosInteres' role='button' data-slide='prev'>";
            html += "			    <span class='carousel-control-prev-icon' aria-hidden='true'></span>";
            html += "			    <span class='sr-only'>Previous</span>";
            html += "			  </a>";
            html += "			  <a class='carousel-control-next' href='#carouselPuntosInteres' role='button' data-slide='next'>";
            html += "			    <span class='carousel-control-next-icon' aria-hidden='true'></span>";
            html += "			    <span class='sr-only'>Next</span>";
            html += "			  </a>";
            html += "			</div>";
            html += "		</div>";
        }
        if (Provincia.ProductosRegionales.length > 0) {
            html += "		<div class='wrapper col-xs-12 col-lg-6'>";
            html += "			<h3>Productos Regionales</h3>";
            html += "			<hr/>";
            html += "			<div id='carouselProductosRegionales' class='carousel slide' data-ride='carousel'>";
            html += "			  <ol class='carousel-indicators'>";
            for (var k = 0; k < Provincia.ProductosRegionales.length; k++) {
                if (k === 0) {
                    html += "			    <li data-target='#carouselProductosRegionales' data-slide-to='" + k + "' class='active'></li>";
                    continue;
                }
                html += "			    <li data-target='#carouselProductosRegionales' data-slide-to='" + k + "'></li>";
            }
            html += "			  </ol>";
            html += "			  <div class='carousel-inner'>";
            for (var l = 0; l < Provincia.ProductosRegionales.length; l++) {
                if (l === 0) {
                    html += "			    <div class='carousel-item active'>";
                }
                else {
                    html += "			    <div class='carousel-item'>";
                }
                html += "				  <img class='d-block w-100 img-fluid' src='" + Provincia.ProductosRegionales[l].Foto + "' alt='" + Provincia.ProductosRegionales[l].Nombre + "'>";
                html += "				  <div class='carousel-caption d-none d-md-block shadow-text'>";
                html += "				    <h2>" + Provincia.ProductosRegionales[l].Nombre + "</h2>";
                html += "				    <h5>" + Provincia.ProductosRegionales[l].Descripcion + "</h5>";
                html += "				  </div>";
                html += "				</div>";
            }
            html += "			  </div>";
            html += "			  <a class='carousel-control-prev' href='#carouselProductosRegionales' role='button' data-slide='prev'>";
            html += "			    <span class='carousel-control-prev-icon' aria-hidden='true'></span>";
            html += "			    <span class='sr-only'>Previous</span>";
            html += "			  </a>";
            html += "			  <a class='carousel-control-next' href='#carouselProductosRegionales' role='button' data-slide='next'>";
            html += "			    <span class='carousel-control-next-icon' aria-hidden='true'></span>";
            html += "			    <span class='sr-only'>Next</span>";
            html += "			  </a>";
            html += "			</div>";
            html += "		</div>";
        }
        html += "	</div>";
        html += "</div>";
        mid.innerHTML = html;
    };
    this.ProvinciaMaestro = function (Provincia) {
        var mid = document.getElementById('mid');
        var html = "";
        html += "<div class='container-fluid text-left text-white'>";
        html += "	<div class='row mt-5'>";
        html += "	  	<div class='col'>";
        html += "		  	<h2>" + Provincia.Nombre + "</h2>";
        html += "			<hr/>";
        html += "	  	</div>";
        html += "	</div>";
        html += "	<div class='row'>";
        html += "		<div class='col-xs-12 col-md-2 text-center'>";
        html += "			<img src='" + Provincia.Foto + "' alt='" + Provincia.Nombre + "' class='img-thumbnail img-fluid' style='height: 25rem;'>";
        html += "		</div>";
        html += "		<div class='col-xs-12 col-md-10 mt-2 align-self-center'>";
        html += "		    <h3 >Capital: " + Provincia.Capital + "</h3>";
        html += "		    <h3 >Poblaci&oacute;n: " + Provincia.Poblacion + "</h3>";
        html += "		    <h3 >Cantidad de Senadores: " + Provincia.CantSenadores + "</h3>";
        html += "		    <h3 >Cantidad de Diputados: " + Provincia.CantDiputados + "</h3>";
        html += "		    <h3 >Superficie (Km2): " + Provincia.Superficie + "</h3>";
        html += "		</div>";
        html += "	</div>";
        html += "	<div class='row mt-5 mb-5'>";
        html += "		<div class='col-xs-12 col-md-9'>";
        html += "			<blockquote class='blockquote d-inline'>";
        html += "			  <h2 class='mb-0'>" + Provincia.Gobernador.Nombre + " " + Provincia.Gobernador.Apellido + " - Gobernador/a</h2>";
        html += "			</blockquote>";
        html += "			<hr/>";
        html += "			<h4>Per&iacute;odo de Gobierno: " + Provincia.Gobernador.PeriodoGobierno + "</h4>";
        html += "			<p class='lead'>" + Provincia.Gobernador.Historial + "</p>";
        html += "		</div>";
        html += "		<div class='col-xs-12 col-md-3 text-center align-self-center'>";
        html += "			<img src='" + Provincia.Gobernador.Foto + "' alt='" + Provincia.Gobernador.Nombre + " " + Provincia.Gobernador.Apellido + "' class='img-thumbnail img-fluid' style='height: 15rem;'>";
        html += "		</div>";
        html += "	</div>";
        html += "	<div class='row text-center mb-5 justify-content-center'>";
        if (Provincia.PuntosDeInteres.length > 0) {
            html += "		<div class='wrapper col-xs-12 col-lg-6'>";
            html += "			<h3>Puntos de Interes</h3>";
            html += "			<hr/>";
            html += "			<div id='carouselPuntosInteres' class='carousel slide' data-ride='carousel'>";
            html += "			  <ol class='carousel-indicators'>";
            for (var i = 0; i < Provincia.PuntosDeInteres.length; i++) {
                if (i === 0) {
                    html += "			    <li data-target='#carouselPuntosInteres' data-slide-to='" + i + "' class='active'></li>";
                    continue;
                }
                html += "			    <li data-target='#carouselPuntosInteres' data-slide-to='" + i + "'></li>";
            }
            html += "			  </ol>";
            html += "			  <div class='carousel-inner'>";
            for (var j = 0; j < Provincia.PuntosDeInteres.length; j++) {
                if (j === 0) {
                    html += "			    <div class='carousel-item active'>";
                }
                else {
                    html += "			    <div class='carousel-item'>";
                }
                html += "				  <img class='d-block w-100 img-fluid' src='" + Provincia.PuntosDeInteres[j].Foto + "' alt='Buenos Aires'>";
                html += "				  <div class='carousel-caption d-none d-md-block shadow-text'>";
                html += "				    <h2>" + Provincia.PuntosDeInteres[j].Nombre + "</h2>";
                html += "				    <h5>" + Provincia.PuntosDeInteres[j].Descripcion + "</h5>";
                html += "				  </div>";
                html += "				</div>";
            }
            html += "			  </div>";
            html += "			  <a class='carousel-control-prev' href='#carouselPuntosInteres' role='button' data-slide='prev'>";
            html += "			    <span class='carousel-control-prev-icon' aria-hidden='true'></span>";
            html += "			    <span class='sr-only'>Previous</span>";
            html += "			  </a>";
            html += "			  <a class='carousel-control-next' href='#carouselPuntosInteres' role='button' data-slide='next'>";
            html += "			    <span class='carousel-control-next-icon' aria-hidden='true'></span>";
            html += "			    <span class='sr-only'>Next</span>";
            html += "			  </a>";
            html += "			</div>";
            html += "		</div>";
        }
        if (Provincia.ProductosRegionales.length > 0) {
            html += "		<div class='wrapper col-xs-12 col-lg-6'>";
            html += "			<h3>Productos Regionales</h3>";
            html += "			<hr/>";
            html += "			<div id='carouselProductosRegionales' class='carousel slide' data-ride='carousel'>";
            html += "			  <ol class='carousel-indicators'>";
            for (var k = 0; k < Provincia.ProductosRegionales.length; k++) {
                if (k === 0) {
                    html += "			    <li data-target='#carouselProductosRegionales' data-slide-to='" + k + "' class='active'></li>";
                    continue;
                }
                html += "			    <li data-target='#carouselProductosRegionales' data-slide-to='" + k + "'></li>";
            }
            html += "			  </ol>";
            html += "			  <div class='carousel-inner'>";
            for (var l = 0; l < Provincia.ProductosRegionales.length; l++) {
                if (l === 0) {
                    html += "			    <div class='carousel-item active'>";
                }
                else {
                    html += "			    <div class='carousel-item'>";
                }
                html += "				  <img class='d-block w-100 img-fluid' src='" + Provincia.ProductosRegionales[l].Foto + "' alt='" + Provincia.ProductosRegionales[l].Nombre + "'>";
                html += "				  <div class='carousel-caption d-none d-md-block shadow-text'>";
                html += "				    <h2>" + Provincia.ProductosRegionales[l].Nombre + "</h2>";
                html += "				    <h5>" + Provincia.ProductosRegionales[l].Descripcion + "</h5>";
                html += "				  </div>";
                html += "				</div>";
            }
            html += "			  </div>";
            html += "			  <a class='carousel-control-prev' href='#carouselProductosRegionales' role='button' data-slide='prev'>";
            html += "			    <span class='carousel-control-prev-icon' aria-hidden='true'></span>";
            html += "			    <span class='sr-only'>Previous</span>";
            html += "			  </a>";
            html += "			  <a class='carousel-control-next' href='#carouselProductosRegionales' role='button' data-slide='next'>";
            html += "			    <span class='carousel-control-next-icon' aria-hidden='true'></span>";
            html += "			    <span class='sr-only'>Next</span>";
            html += "			  </a>";
            html += "			</div>";
            html += "		</div>";
        }
        html += "	</div>";
        html += "   <hr/>";
        html += "   <div class='row text-center'>";
        html += "   	<div class='col-12'>";
        html += "   		<button type='button' class='btn btn-info shadow-sm rounded my-4' data-toggle='modal' data-target='#VModalAlumnos' onclick='Event0.RefrescarCampoNota();'>";
        html += "   		  Asignar Nota";
        html += "   		</button>";
        html += "   	</div>";
        html += "   </div>";
        html += "   <div id='VModalAlumnos' class='modal fade' tabindex='-1' role='dialog'>";
        html += "     <div class='modal-dialog' role='document'>";
        html += "       <div class='modal-content bg-gradient-custom text-white'>";
        html += "         <div class='modal-header'>";
        html += "           <h5 class='modal-title'>Calificar</h5>";
        html += "           <button type='button' class='close' data-dismiss='modal' aria-label='Close'>";
        html += "             <span aria-hidden='true'>&times;</span>";
        html += "           </button>";
        html += "         </div>";
        html += "         <div class='modal-body'>";
        html += "   		<form class='form-group'>";
        html += "       		<p>Seleccione la Nota:</p>";
        html += "       		<input type='text' min='0' max='10' id='TBCalificacion' class='form-control my-2' value='" + Provincia.Nota + "' />";
        html += "   		</form>";
        html += "         </div>";
        html += "         <div class='modal-footer'>";
        html += "           <button type='button' class='btn btn-info shadow-sm' data-dismiss='modal' onclick='Event0.RefrescarCampoNota();'>Cancelar</button>";
        html += "           <button type='button' class='btn btn-info shadow-sm' data-dismiss='modal' onclick='Event0.AsignarNota(" + Provincia.ID + ");'>Guardar Cambios</button>";
        html += "         </div>";
        html += "       </div>";
        html += "     </div>";
        html += "   </div>";
        html += "</div>";
        mid.innerHTML = html;
    };
    this.ProvinciaGrupo = function (Provincia) {
        var mid = document.getElementById('mid');
        var html = "";
        html += "<div class='container-fluid text-white'>";
        html += "  <div class='row text-center mt-2'>";
        html += "  	<div class='col-12'>";
        html += "	  	<h1>" + Provincia.Nombre + "</h1>";
        html += "	  	<hr/>";
        html += "  	</div>";
        html += "  </div>";
        html += "  <div>";
        html += "   <form id='formProvincia' class='row' method='POST' action='Default.aspx' enctype='multipart/form-data' target='iframeProvincia' >";
        html += "       <input type='hidden' name='Accion' value='ModificarProvincia' />";
        html += "       <input type='hidden' name='IDProvincia' value='" + Provincia.ID + "' />";
        html += "	    <div class='col-xs-12 col-md-6 d-block'>";
        html += "	        <legend>Informaci&oacute;n requerida</legend>";
        html += "	        <div class='form-group'>";
        html += "	          <label for='TBCapital'>Capital</label>";
        html += "	          <input type='text' class='form-control' id='TBCapital' name='TBCapital' maxlength='40' value='" + Provincia.Capital + "'>";
        html += "	        </div>";
        html += "	        <div class='form-group'>";
        html += "	          <label for='TBPoblacion'>Poblaci&oacute;n</label>";
        html += "	          <input type='text' class='form-control' id='TBPoblacion' name='TBPoblacion' value='" + Provincia.Poblacion + "'>";
        html += "	        </div>";
        html += "	        <div class='form-group'>";
        html += "	          <label for='TBSuperficie'>Superficie (Km2)</label>";
        html += "	          <input type='text' class='form-control' id='TBSuperficie' name='TBSuperficie' value='" + Provincia.Superficie + "'>";
        html += "	        </div>";
        html += "	        <div class='form-group'>";
        html += "	          <label for='TBSenadores'>Cantidad de Senadores</label>";
        html += "	          <input type='text' class='form-control' id='TBSenadores' name='TBSenadores' value='" + Provincia.CantSenadores + "'>";
        html += "	        </div>";
        html += "	        <div class='form-group'>";
        html += "	          <label for='TBDiputados'>Cantidad de Diputados</label>";
        html += "	          <input type='text' class='form-control' id='TBDiputados' name='TBDiputados' value='" + Provincia.CantDiputados + "'>";
        html += "	        </div>";
        html += "	        <div class='form-group'>";
        html += "	          <label for='TBMapa'>Mapa de la Provincia</label>";
        html += "	          <input type='file' class='form-control-file' id='TBMapa' name='TBMapa' aria-describedby='LBMapa' onchange='Event0.CargarMapa();'>";
        html += "	          <small id='LBMapa' class='form-text text-light'>Seleccione el mapa de la provincia.</small>";
        html += "	        </div>";
        html += "	        <div class='form-group text-center'>";
        html += "	    		<img src='" + Provincia.Foto + "' id='IMGMapa' class='rounded img-fluid mt-2 shadow-lg' style='max-height: 50vh;'>";
        html += "	    	</div>";
        html += "	    </div>";
        html += "	    <div class='col-xs-12 col-md-6 d-block'>";
        html += "	        <legend>Gobernador/a</legend>";
        html += "	        <div class='form-group'>";
        html += "	          <label for='TBNombre'>Nombre</label>";
        html += "	          <input type='text' class='form-control' id='TBNombre' name='TBNombre' maxlength='40' value='" + Provincia.Gobernador.Nombre + "'>";
        html += "	        </div>";
        html += "	        <div class='form-group'>";
        html += "	          <label for='TBApellido'>Apellido</label>";
        html += "	          <input type='text' class='form-control' id='TBApellido' name='TBApellido' maxlength='40' value='" + Provincia.Gobernador.Apellido + "'>";
        html += "	        </div>";
        html += "	        <div class='form-group'>";
        html += "	          <label for='TBPeriodo'>Periodo de Gobierno</label>";
        html += "	          <input type='text' class='form-control' id='TBPeriodo' name='TBPeriodo' maxlength='30' value='" + Provincia.Gobernador.PeriodoGobierno + "'>";
        html += "	        </div>";
        html += "	        <div class='form-group'>";
        html += "	          <label for='TBHistorial'>Historial</label>";
        html += "	          <textarea class='form-control' id='TBHistorial' name='TBHistorial' rows='3'>" + Provincia.Gobernador.Historial + "</textarea>";
        html += "	        </div>";
        html += "	        <div class='form-group'>";
        html += "	          <label for='TBGobernador'>Foto</label>";
        html += "	          <input type='file' class='form-control-file' id='TBGobernador' name='TBGobernador' aria-describedby='LBGobernador' onchange='Event0.CargarGobernador();'>";
        html += "	          <small id='LBGobernador' class='form-text text-light'>Seleccione la imagen del gobernador sobre el cual quieren hablar.</small>";
        html += "	        </div>";
        html += "	    	<div class='form-group text-center'>";
        html += "	    		<img src='" + Provincia.Gobernador.Foto + "' id='IMGGobernador' name='IMGGobernador' class='rounded img-fluid mt-2 shadow-lg' style='max-height: 50vh;'>";
        html += "	    	</div>";
        html += "	    </div>";
        html += "   </form>";
        html += "   <iframe id='iframeProvincia' name='iframeProvincia' class='d-none'></iframe>";
        html += "   <div class='row text-center mt-2'>";
        html += "    	<div class='col-12'>";
        html += "    		<button class='btn btn-info shadow-sm' onclick='Event0.GuardarProvincia();'>Guardar Cambios</button>";
        html += "    	</div>";
        html += "   </div>";
        html += "  </div>";
        html += "</div>";
        html += "<hr/>";
        html += "<div class='container-fluid'>";
        html += "	<div class='row text-center mb-1 justify-content-center'>";
        html += "		<div class='col-xs-12 col-lg-6'>";
        html += "			<div class='row justify-content-center'>";
        html += "				<h3>Puntos de Interes</h3>";
        html += "				<button type='button' class='btn btn-info shadow-sm ml-2' data-toggle='modal' data-target='#VModalAgregarPDeInt' >";
        html += "				  <img src='Imagenes/Iconos/add.png' class='img-fluid' style='height: 1.5rem;'>";
        html += "				</button>";
        html += "			</div>";
        html += "			<hr/>";
        html += "			<div id='tablaPuntosDeInteres'>";
        html += "			</div>";
        html += "		</div>";
        html += "		<div class='col-xs-12 col-lg-6'>";
        html += "			<div class='row justify-content-center'>";
        html += "				<h3>Productos Regionales</h3>";
        html += "				<button type='button' class='btn btn-info shadow-sm ml-2' data-toggle='modal' data-target='#VModalAgregarProdReg' >";
        html += "				  <img src='Imagenes/Iconos/add.png' class='img-fluid' style='height: 1.5rem;'>";
        html += "				</button>";
        html += "			</div>";
        html += "			<hr/>";
        html += "			<div id='tablaProductosRegionales'>";
        html += "			</div>";
        html += "		</div>";
        html += "	</div>";
        html += "   <div id='VModalAgregarProdReg' class='modal fade' tabindex='-1' role='dialog'>";
        html += "     <div class='modal-dialog' role='document'>";
        html += "       <div class='modal-content bg-gradient-custom text-white'>";
        html += "         <div class='modal-header'>";
        html += "           <h5 class='modal-title'>Producto Regional</h5>";
        html += "           <button type='button' class='close' data-dismiss='modal' aria-label='Close'>";
        html += "             <span aria-hidden='true'>&times;</span>";
        html += "           </button>";
        html += "         </div>";
        html += "         <div class='modal-body'>";
        html += "           <form id='formAPR' class='form' method='POST' action='Default.aspx' enctype='multipart/form-data' target='iframePR' >";
        html += "               <input type='hidden' id='Accion' name='Accion' value='AgregarProductoRegional' />";
        html += "               <input type='hidden' id='IDProvincia' name='IDProvincia' value='" + Provincia.ID + "' />";
        html += "   		    <div class='form-group'>";
        html += "       	    	<p>Nombre:</p>";
        html += "       	    	<input type='text' id='TBNombrePR' name='TBNombrePR' class='form-control my-2' maxlength='60' />";
        html += "   		    </div>";
        html += "       	    <div class='form-group'>";
        html += "       	    	<p>Descripci&oacute;n:</p>";
        html += "       	    	<textarea type='text' id='TBDescripcionPR' name='TBDescripcionPR' class='form-control my-2' rows='3' ></textarea>";
        html += "       	    </div>";
        html += "       	    <div class='form-group'>";
        html += "       	    	<p>Foto:</p>";
        html += "       	    	<input type='file' id='TBFotoPR' name='TBFotoPR' class='form-control my-2'>";
        html += "       	    </div>";
        html += "           </form>";
        html += "           <iframe id='iframePR' name='iframePR' class='d-none'></iframe>";
        html += "         </div>";
        html += "         <div class='modal-footer'>";
        html += "           <button type='button' class='btn btn-info shadow-sm' data-dismiss='modal'>Cancelar</button>";
        html += "           <button type='button' class='btn btn-info shadow-sm' data-dismiss='modal' onclick='Event0.AgregarProductoRegional();'>Guardar</button>";
        html += "         </div>";
        html += "       </div>";
        html += "     </div>";
        html += "   </div>";
        html += "   <div id='VModalAgregarPDeInt' class='modal fade' tabindex='-1' role='dialog'>";
        html += "     <div class='modal-dialog' role='document'>";
        html += "       <div class='modal-content bg-gradient-custom text-white'>";
        html += "         <div class='modal-header'>";
        html += "           <h5 class='modal-title'>Punto de Inter&eacute;s</h5>";
        html += "           <button type='button' class='close' data-dismiss='modal' aria-label='Close'>";
        html += "             <span aria-hidden='true'>&times;</span>";
        html += "           </button>";
        html += "         </div>";
        html += "         <div class='modal-body'>";
        html += "           <form id='formAPI' class='form' method='POST' action='Default.aspx' enctype='multipart/form-data' target='iframePI' >";
        html += "               <input type='hidden' id='Accion' name='Accion' value='AgregarPuntoDeInteres' />";
        html += "               <input type='hidden' id='IDProvincia' name='IDProvincia' value='" + Provincia.ID + "' />";
        html += "   		    <div class='form-group'>";
        html += "       	    	<p>Nombre:</p>";
        html += "       	    	<input type='text' id='TBNombrePI' name='TBNombrePI' class='form-control my-2' maxlength='60' />";
        html += "   		    </div>";
        html += "       	    <div class='form-group'>";
        html += "       	    	<p>Descripci&oacute;n:</p>";
        html += "       	    	<textarea type='text' id='TBDescripcionPI' name='TBDescripcionPI' class='form-control my-2' rows='3' ></textarea>";
        html += "       	    </div>";
        html += "       	    <div class='form-group'>";
        html += "       	    	<p>Foto:</p>";
        html += "       	    	<input type='file' id='TBFotoPI' name='TBFotoPI' class='form-control my-2'>";
        html += "       	    </div>";
        html += "           </form>";
        html += "           <iframe id='iframePI' name='iframePI' class='d-none'></iframe>";
        html += "         </div>";
        html += "         <div class='modal-footer'>";
        html += "           <button type='button' class='btn btn-info shadow-sm' data-dismiss='modal'>Cancelar</button>";
        html += "           <button type='button' class='btn btn-info shadow-sm' data-dismiss='modal' onclick='Event0.AgregarPuntoDeInteres();'>Guardar</button>";
        html += "         </div>";
        html += "       </div>";
        html += "     </div>";
        html += "   </div>";
        html += "   <div id='VModalImagen' class='modal fade' tabindex='-1' role='dialog'>";
        html += "   </div>";
        html += "   <div id='VModalEditarPR' class='modal fade' tabindex='-1' role='dialog'>";
        html += "   </div>";
        html += "   <div id='VModalEditarPI' class='modal fade' tabindex='-1' role='dialog'>";
        html += "   </div>";
        html += "</div>";
        mid.innerHTML = html;
        ListarPuntosDeInteres();
        ListarProductosRegionales();
    };
    this.ModalImagen = function (Indicador) {
        var modal = document.getElementById('VModalImagen');
        var html = "";
        html += "     <div class='modal-dialog' role='document' >";
        html += "       <div class='modal-content text-center text-white bg-gradient-custom' >";
        html += "         <div class='modal-header'>";
        html += "           <h5 class='modal-title'>" + Indicador.Nombre + "</h5>";
        html += "           <button type='button' class='close' data-dismiss='modal' aria-label='Close'>";
        html += "             <span aria-hidden='true'>&times;</span>";
        html += "           </button>";
        html += "         </div>";
        html += "         <div class='modal-body'>";
        html += "           <img src='" + Indicador.Foto + "' class='d-block w-100 img-fluid img-thumbnail'";
        html += "   		<p class='lead d-block'>" + Indicador.Descripcion + "</p>";
        html += "         </div>";
        html += "         <div class='modal-footer'>";
        html += "           <button type='button' class='btn btn-info shadow-sm' data-dismiss='modal'>Cerrar</button>";
        html += "         </div>";
        html += "       </div>";
        html += "     </div>";
        modal.innerHTML = html;
    };
    this.ModalEditarPR = function (ProductoRegional, index, idProvincia) {
        var modal = document.getElementById('VModalEditarPR');
        var html = "";
        html += "     <div class='modal-dialog' role='document' >";
        html += "       <div class='modal-content text-white bg-gradient-custom' >";
        html += "         <div class='modal-header'>";
        html += "           <h5 class='modal-title'>Producto Regional</h5>";
        html += "           <button type='button' class='close' data-dismiss='modal' aria-label='Close'>";
        html += "             <span aria-hidden='true'>&times;</span>";
        html += "           </button>";
        html += "         </div>";
        html += "         <div class='modal-body'>";
        html += "           <form id='formMPR' class='form' method='POST' action='Default.aspx' enctype='multipart/form-data' target='iframeMPR' >";
        html += "               <input type='hidden' id='Accion' name='Accion' value='ModificarProductoRegional' />";
        html += "               <input type='hidden' id='IDProvincia' name='IDProvincia' value='" + idProvincia + "' />";
        html += "               <input type='hidden' id='IDProductoRegional' name='IDProductoRegional' value='" + ProductoRegional.ID + "' />";
        html += "               <div class='form-group'>";
        html += "                   <label>Nombre</label>";
        html += "   		        <input id='TBENombrePR' name='TBENombrePR' type='text' class='form-control' value='" + ProductoRegional.Nombre + "' maxlength='60' />";
        html += "               </div>";
        html += "               <div class='form-group'>";
        html += "                   <label>Descripci&oacute;n</label>";
        html += "   		        <textarea id='TBEDescripcionPR' name='TBEDescripcionPR' class='form-control' rows='3'>" + ProductoRegional.Descripcion + "</textarea>";
        html += "               </div>";
        html += "               <div class='form-group'>";
        html += "                 <label for='TBEFotoPR'>Foto</label>";
        html += "		          <input type='file' class='form-control-file' id='TBEFotoPR' name='TBEFotoPR' aria-describedby='LBEFotoPR'>";
        html += "		          <small id='LBEFotoPR' class='form-text text-light'>Recuerde: Si selecciona otra imagen la actual se reemplazar&aacute;.</small>";
        html += "               </div>";
        html += "           </form>";
        html += "           <iframe id='iframeMPR' name='iframeMPR' class='d-none'></iframe>";
        html += "         </div>";
        html += "         <div class='modal-footer'>";
        html += "           <button type='button' class='btn btn-info shadow-sm' data-dismiss='modal'>Cerrar</button>";
        html += "           <button type='button' class='btn btn-info shadow-sm' data-dismiss='modal' onclick='Event0.ModificarProductoRegional(" + index + ");'>Guardar Cambios</button>";
        html += "         </div>";
        html += "       </div>";
        html += "     </div>";
        modal.innerHTML = html;
    };
    this.ModalEditarPI = function (PuntoDeInteres, index, idProvincia) {
        var modal = document.getElementById('VModalEditarPI');
        var html = "";
        html += "     <div class='modal-dialog' role='document' >";
        html += "       <div class='modal-content text-white bg-gradient-custom' >";
        html += "         <div class='modal-header'>";
        html += "           <h5 class='modal-title'>Punto de Inter&eacute;s</h5>";
        html += "           <button type='button' class='close' data-dismiss='modal' aria-label='Close'>";
        html += "             <span aria-hidden='true'>&times;</span>";
        html += "           </button>";
        html += "         </div>";
        html += "         <div class='modal-body'>";
        html += "           <form id='formMPI' class='form' method='POST' action='Default.aspx' enctype='multipart/form-data' target='iframeMPI' >";
        html += "               <input type='hidden' id='Accion' name='Accion' value='ModificarPuntoDeInteres' />";
        html += "               <input type='hidden' id='IDProvincia' name='IDProvincia' value='" + idProvincia + "' />";
        html += "               <input type='hidden' id='IDPuntoDeInteres' name='IDPuntoDeInteres' value='" + PuntoDeInteres.ID + "' />";
        html += "               <div class='form-group'>";
        html += "                   <label>Nombre</label>";
        html += "   		        <input id='TBENombrePI' name='TBENombrePI' type='text' class='form-control' value='" + PuntoDeInteres.Nombre + "' maxlength='60' />";
        html += "               </div>";
        html += "               <div class='form-group'>";
        html += "                   <label>Descripci&oacute;n</label>";
        html += "   		        <textarea id='TBEDescripcionPI' name='TBEDescripcionPI' class='form-control' rows='3'>" + PuntoDeInteres.Descripcion + "</textarea>";
        html += "               </div>";
        html += "               <div class='form-group'>";
        html += "                 <label for='TBEFotoPI'>Foto</label>";
        html += "		          <input type='file' class='form-control-file' id='TBEFotoPI' name='TBEFotoPI' aria-describedby='LBEFotoPI'>";
        html += "		          <small id='LBEFotoPI' class='form-text text-light'>Recuerde: Si selecciona otra imagen la actual se reemplazar&aacute;.</small>";
        html += "               </div>";
        html += "           </form>";
        html += "           <iframe id='iframeMPI' name='iframeMPI' class='d-none'></iframe>";
        html += "         </div>";
        html += "         <div class='modal-footer'>";
        html += "           <button type='button' class='btn btn-info shadow-sm' data-dismiss='modal'>Cerrar</button>";
        html += "           <button type='button' class='btn btn-info shadow-sm' data-dismiss='modal' onclick='Event0.ModificarPuntoDeInteres(" + index + ");'>Guardar Cambios</button>";
        html += "         </div>";
        html += "       </div>";
        html += "     </div>";
        modal.innerHTML = html;
    };
    this.PantallaAlumnos = function (Provincias) {
        var mid = document.getElementById('mid');
        var html = "";
        html += "<div class='container mt-5 mb-5 text-center h-100'>";
        html += "  	<div class='row justify-content-center text-white'>";
        html += "		<h3>Listado de Alumnos</h3>";
        html += "		<button type='button' class='btn btn-info shadow-sm ml-2' data-toggle='modal' data-target='#VModalAAlumno' >";
        html += "		  <img src='Imagenes/Iconos/add.png' class='img-fluid' style='height: 1.5rem;'>";
        html += "		</button>";
        html += "	</div>";
        html += "	<hr/>";
        html += "	<div class='row justify-content-left my-4 text-white'>";
        html += "		<div class='form-inline col-xs-12 col-md-6'>";
        html += "			<label for='TBFiltro' class='mx-2'>Filtrar</label>";
        html += "			<input type='text' id='TBFiltro' onkeyup='Event0.FiltrarTablaAlumnos();' class='form-control mx-2' placeholder='Ingrese texto...' />";
        html += "		</div>";
        html += "	</div>";
        html += "	<div id='tablaAlumnos'>";
        html += "	</div>";
        html += "    <div class='row text-center mt-4'>";
        html += "    	<div class='col-12'>";
        html += "    		<button type='submit' class='btn btn-info shadow-sm' data-toggle='modal' data-target='#VModalPDF' onclick='Event0.VerNotas();'>Ver Notas</button>";
        html += "    	</div>";
        html += "    </div>";
        html += "</div>";
        html += "<div id='VModalAAlumno' class='modal fade' tabindex='-1' role='dialog'>";
        html += "  <div class='modal-dialog' role='document'>";
        html += "    <div class='modal-content bg-gradient-custom text-white'>";
        html += "       <div class='modal-header'>";
        html += "         <h5 class='modal-title'>Alumno</h5>";
        html += "         <button type='button' class='close' data-dismiss='modal' aria-label='Close'>";
        html += "           <span aria-hidden='true'>&times;</span>";
        html += "         </button>";
        html += "       </div>";
        html += "       <div class='modal-body'>";
        html += "           <div class='form-group'>";
        html += "           	<p>Nombre Completo</p>";
        html += "           	<input type='text' id='TBNombreA' class='form-control my-2' maxlength='50' />";
        html += "           </div>";
        html += "           <div class='form-group'>";
        html += "           	<p>D.N.I.</p>";
        html += "           	<input type='text' id='TBDNIA' class='form-control my-2' />";
        html += "           </div>";
        html += "           <div class='form-group'>";
        html += "               <p>Grupo</p>";
        html += "               <select class='form-control' id='CBGrupoA'>";
        for (var i = 0; i < Provincias.length; i++) {
            html += "                   <option value='" + Provincias[i].ID + "'>" + Provincias[i].Nombre + "</option>";
        }
        html += "               </select>";
        html += "           </div>";
        html += "      </div>";
        html += "      <div class='modal-footer'>";
        html += "        <button type='button' class='btn btn-info shadow-sm' data-dismiss='modal'>Cancelar</button>";
        html += "        <button type='submit' class='btn btn-info shadow-sm' data-dismiss='modal' onclick='Event0.AgregarAlumno();'>Guardar</button>";
        html += "      </div>";
        html += "    </div>";
        html += "  </div>";
        html += "</div>";
        html += "<div id='VModalEAlumno' class='modal fade' tabindex='-1' role='dialog'>";
        html += "</div>";
        html += "<div id='VModalPDF' class='modal fade' tabindex='-1' role='dialog'>";
        html += "</div>";
        mid.innerHTML = html;
        ListarAlumnos();
    };
    this.ModalEditarA = function (Alumno, index, Provincias) {
        var modal = document.getElementById('VModalEAlumno');
        var html = "";
        html += "  <div class='modal-dialog' role='document'>";
        html += "    <div class='modal-content bg-gradient-custom text-white'>";
        html += "      <div class='modal-header'>";
        html += "        <h5 class='modal-title'>Editar Alumno</h5>";
        html += "        <button type='button' class='close' data-dismiss='modal' aria-label='Close'>";
        html += "          <span aria-hidden='true'>&times;</span>";
        html += "        </button>";
        html += "      </div>";
        html += "      <div class='modal-body'>";
        html += "		<div class='form-group'>";
        html += "    		<p>Nombre Completo</p>";
        html += "    		<input type='text' id='TBENombreA' class='form-control my-2' maxlength='50' value='" + Alumno.Nombre + "' />";
        html += "		</div>";
        html += "    	<div class='form-group'>";
        html += "    		<p>D.N.I.</p>";
        html += "    		<input type='text' id='TBEDNIA' class='form-control my-2' value='" + Alumno.DNI + "' />";
        html += "    	</div>";
        html += "       <div class='form-group'>";
        html += "           <p>Grupo</p>";
        html += "           <select class='form-control' id='CBEGrupoA'>";
        for (var i = 0; i < Provincias.length; i++) {
            if (Alumno.Grupo.ID === Provincias[i].ID) {
                html += "               <option selected value='" + Provincias[i].ID + "'>" + Provincias[i].Nombre + "</option>";
            }
            else {
                html += "               <option value='" + Provincias[i].ID + "'>" + Provincias[i].Nombre + "</option>";
            }
        }
        html += "           </select>";
        html += "       </div>";
        html += "      </div>";
        html += "      <div class='modal-footer'>";
        html += "        <button type='button' class='btn btn-info shadow-sm' data-dismiss='modal'>Cancelar</button>";
        html += "        <button type='button' class='btn btn-info shadow-sm' data-dismiss='modal' onclick='Event0.ModificarAlumno(" + Alumno.ID + ", " + index + ");'>Guardar</button>";
        html += "      </div>";
        html += "    </div>";
        html += "  </div>";
        modal.innerHTML = html;
    };
    this.ModalPDF = function (doc) {
        modal = document.getElementById('VModalPDF');
        var html = "";
        html += "  <div class='modal-dialog framePDF' role='document'>";
        html += "    <div class='modal-content bg-gradient-custom text-white'>";
        html += "      <div class='modal-header'>";
        html += "        <h5 class='modal-title'>Notas</h5>";
        html += "        <button type='button' class='close' data-dismiss='modal' aria-label='Close'>";
        html += "          <span aria-hidden='true'>&times;</span>";
        html += "        </button>";
        html += "      </div>";
        html += "      <div class='modal-body' style='height: 40rem !important;'>";
        html += "        <iframe width='100%' height='100%' src='" + doc.output('datauristring') + "'></iframe>";
        html += "      </div>";
        html += "      <div class='modal-footer'>";
        html += "        <button type='button' class='btn btn-info shadow-sm' data-dismiss='modal'>Cancelar</button>";
        html += "      </div>";
        html += "    </div>";
        html += "  </div>";
        modal.innerHTML = html;
    };
    this.EditarPerfil = function () {
        var mid = document.getElementById('mid');
        var html = "";
        html += "<div class='container text-white'>";
        html += "	<form id='formEPerfil' class='row align-items-center' method='POST' action='Default.aspx' enctype='multipart/form-data' target='iframeEPerfil'>";
        html += "       <input type='hidden' name='Accion' value='EditarPerfil' />";
        html += "       <input type='hidden' name='IDUsuario' value='" + Usuario.ID + "' />";
        html += "		<div class='col-xs-12 col-md-8'>";
        html += "			<div class='container mt-5 mb-5 text-left'>";
        html += "				<div class='form-group row'>";
        html += "			      <label for='TBClaveActual' class='col-sm-3 col-form-label'>Contraseña Actual</label>";
        html += "			      <div class='col-sm-9 '>";
        html += "			        <input type='password' class='form-control w-50 shadow-sm' id='TBClaveActual'>";
        html += "			      </div>";
        html += "			    </div>";
        html += "			    <div class='form-group row'>";
        html += "			      <label for='TBClaveNueva' class='col-sm-3 col-form-label'>Nueva Contraseña</label>";
        html += "			      <div class='col-sm-9'>";
        html += "			        <input type='password' class='form-control w-50 shadow-sm' id='TBClaveNueva'>";
        html += "			      </div>";
        html += "			    </div>";
        html += "			    <div class='form-group row'>";
        html += "			      <label for='TBClaveNueva2' class='col-sm-3 col-form-label'>Repetir Contraseña</label>";
        html += "			      <div class='col-sm-9'>";
        html += "			        <input type='password' class='form-control w-50 shadow-sm' id='TBClaveNueva2' name='TBClaveNueva2'>";
        html += "			      </div>";
        html += "			    </div>";
        html += "			    <div class='form-group row'>";
        html += "			      <label for='TBFotoUsuario' class='col-sm-3 col-form-label'>Foto</label>";
        html += "			      <div class='col-sm-9'>";
        html += "			        <input type='file' class='form-control w-75 shadow-sm' id='TBFotoUsuario' name='TBFotoUsuario' onchange='Event0.CargarImagenUsuario();'>";
        html += "			      </div>";
        html += "			    </div>";
        html += "			</div>";
        html += "		</div>";
        html += "		<div class='col-xs-12 col-md-4'>";
        html += "			<div class='container mt-5 mb-5'>";
        html += "				<img id='IMGPerfil' src='" + Usuario.Foto + "' class='img-fluid rounded border shadow-lg' style='max-height: 25rem;'>";
        html += "			</div>";
        html += "		</div>";
        html += "	</form>";
        html += "   <iframe id='iframeEPerfil' name='iframeEPerfil' class='d-none'></iframe>";
        html += "   <div class='row justify-content-center'>";
        html += "   	<div class='col-xs-12'>";
        html += "   		<button type='button' class='btn btn-info shadow-sm' onclick='Event0.EditarPerfil();'>Guardar Cambios</button>";
        html += "   	</div>";
        html += "   </div>";
        html += "</div>";
        mid.innerHTML = html;
    };
}